# Generated by Django 6.0.5 on 2026-05-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('guided', 'Guided'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='advanced', max_length=16)),
                ('onboarding_step', models.IntegerField(default=0)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_mode', models.CharField(choices=[('off', 'Off'), ('advisory', 'Advisory'), ('shadow', 'Shadow')], default='off', max_length=16)),
                ('ai_explain_always', models.BooleanField(default=False)),
                ('ai_min_data_days', models.IntegerField(default=30)),
                ('ai_max_auto_actions_day', models.IntegerField(default=0)),
                ('ai_cooldown_minutes', models.IntegerField(default=60)),
                ('ai_shadow_log_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
