# Generated by Django 6.0.5 on 2026-05-07 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_usermode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('change_type', models.CharField(max_length=64)),
                ('target_chan_id', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('actor', models.CharField(max_length=128)),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('rationale', models.JSONField(blank=True, default=dict)),
                ('policy_run_ref', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chan_id', models.CharField(db_index=True, max_length=20)),
                ('local_balance', models.BigIntegerField()),
                ('remote_balance', models.BigIntegerField()),
                ('capacity', models.BigIntegerField()),
                ('local_fee_rate', models.IntegerField(default=0)),
                ('local_base_fee', models.IntegerField(default=0)),
                ('local_disabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['chan_id', 'timestamp'], name='gui_channel_chan_id_77ec34_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForwardingAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.CharField(choices=[('1d', '1d'), ('7d', '7d'), ('30d', '30d')], max_length=4)),
                ('chan_id', models.CharField(db_index=True, max_length=20)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('in_msat', models.BigIntegerField(default=0)),
                ('out_msat', models.BigIntegerField(default=0)),
                ('fees_msat', models.BigIntegerField(default=0)),
                ('forward_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('window', 'chan_id', 'window_start')},
            },
        ),
    ]
