# Generated by Django 6.0.5 on 2026-05-07 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_changelog_channelsnapshot_forwardingaggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('backup_type', models.CharField(choices=[('settings', 'Settings JSON'), ('database', 'Database Dump')], max_length=16)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], default='ok', max_length=16)),
                ('actor', models.CharField(default='manual', max_length=128)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RenameIndex(
            model_name='channelsnapshot',
            new_name='gui_channel_channel_76dc86_idx',
            old_name='gui_channel_channel_2ceb07_idx',
        ),
    ]
