# Generated by Django 6.0.5 on 2026-05-08 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_backup_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy_type', models.CharField(choices=[('auto_fee', 'Auto Fee'), ('rebalance', 'Rebalance'), ('notify', 'Notify')], max_length=20)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('dry_run', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('mode_required', models.CharField(choices=[('guided', 'Guided'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='advanced', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('rec_type', models.CharField(choices=[('open', 'Open Channel'), ('splice_in', 'Splice In'), ('splice_out', 'Splice Out'), ('close', 'Close / Deprioritize'), ('rebalance', 'Rebalance'), ('fee', 'Fee Strategy')], max_length=20)),
                ('target_chan_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('target_pubkey', models.CharField(blank=True, max_length=66, null=True)),
                ('rationale', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('confidence_label', models.CharField(choices=[('heuristic', 'Heuristic'), ('rule_based', 'Rule Based'), ('ml_shadow', 'ML Shadow'), ('ml_model', 'ML Model')], default='heuristic', max_length=16)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('dry_run_result', models.JSONField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('was_dry_run', models.BooleanField(default=True)),
                ('trigger_data', models.JSONField(blank=True, default=dict)),
                ('actions_taken', models.JSONField(blank=True, default=dict)),
                ('outcome', models.JSONField(blank=True, default=dict)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.policy')),
            ],
        ),
        migrations.CreateModel(
            name='SpliceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=20)),
                ('splice_type', models.CharField(choices=[('in', 'Splice In'), ('out', 'Splice Out')], max_length=5)),
                ('amount_sat', models.BigIntegerField()),
                ('on_chain_fee_sat', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('broadcast', 'Broadcast'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('txid', models.CharField(blank=True, default='', max_length=64)),
                ('initiated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.recommendation')),
            ],
            options={
                'indexes': [models.Index(fields=['channel_id', 'initiated_at'], name='gui_splicel_channel_33e5e5_idx')],
            },
        ),
    ]
