# Generated by Django 6.0.5 on 2026-05-08 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_phase4_policy_ml_records'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='autofeemlrecord',
            new_name='gui_autofee_chan_id_93fc07_idx',
            old_name='gui_autofee_chan_id_e081db_idx',
        ),
        migrations.RenameIndex(
            model_name='rebalancemlrecord',
            new_name='gui_rebalan_source__42ee3d_idx',
            old_name='gui_rebalan_source__90b5a4_idx',
        ),
        migrations.AlterField(
            model_name='autofeemlrecord',
            name='ml_confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='rebalancemlrecord',
            name='ml_confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='rebalancemlrecord',
            name='ml_predicted_success_prob',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
