# Generated by Django 6.0.5 on 2026-05-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_rename_gui_autofee_chan_id_e081db_idx_gui_autofee_chan_id_93fc07_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='amboss_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='amboss_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='mempool_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='notify_mempool_low_fee',
            field=models.BooleanField(default=False),
        ),
    ]
