# Generated by Django 6.0.5 on 2026-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_phase5_external_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermode',
            name='ai_policy_bound_confirm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usermode',
            name='ai_mode',
            field=models.CharField(choices=[('off', 'Off'), ('advisory', 'Advisory'), ('shadow', 'Shadow'), ('policy_bound', 'Policy-Bound (Expert)')], default='off', max_length=16),
        ),
    ]
