from django.urls import path

from .views import (
    backup_create,
    backup_list,
    backup_restore,
    capabilities,
    chart_channel_health,
    chart_fee_volume,
    chart_liquidity,
    cleaner_counts,
    cleaner_run,
    cleaner_settings,
    cockpit_stats,
    health,
    ml_autofee_history,
    ml_execute_action,
    ml_autofee_suggestions,
    ml_escalation_config,
    ml_rebalance_train,
    ml_status,
    network_peers,
    policy_run,
    recommendation_dry_run,
    splice_in,
    splice_out,
    splice_preview,
    splice_status,
    sse_live_events,
    user_settings,
)

urlpatterns = [
    path("health/", health, name="api-v2-health"),
    path("user/settings/", user_settings, name="api-v2-user-settings"),
    path("cockpit/", cockpit_stats, name="api-v2-cockpit"),
    path("capabilities/", capabilities, name="api-v2-capabilities"),
    path("charts/liquidity/", chart_liquidity, name="api-v2-chart-liquidity"),
    path("charts/channel-health/", chart_channel_health, name="api-v2-chart-channel-health"),
    path("charts/fee-volume/", chart_fee_volume, name="api-v2-chart-fee-volume"),
    path("cleaner/run/", cleaner_run, name="api-v2-cleaner-run"),
    path("cleaner/settings/", cleaner_settings, name="api-v2-cleaner-settings"),
    path("cleaner/counts/", cleaner_counts, name="api-v2-cleaner-counts"),
    path("recommendations/<int:recommendation_id>/dryrun/", recommendation_dry_run, name="api-v2-recommendation-dryrun"),
    path("policies/<int:policy_id>/run/", policy_run, name="api-v2-policy-run"),
    path("channels/<str:channel_id>/splice/preview/", splice_preview, name="api-v2-splice-preview"),
    path("channels/<str:channel_id>/splice/in/", splice_in, name="api-v2-splice-in"),
    path("channels/<str:channel_id>/splice/out/", splice_out, name="api-v2-splice-out"),
    path("channels/<str:channel_id>/splice/status/", splice_status, name="api-v2-splice-status"),
    path("backup/create/", backup_create, name="api-v2-backup-create"),
    path("backup/restore/", backup_restore, name="api-v2-backup-restore"),
    path("backup/", backup_list, name="api-v2-backup-list"),
    # Phase-6 ML endpoints
    path("ml/status/", ml_status, name="api-v2-ml-status"),
    path("ml/rebalance/train/", ml_rebalance_train, name="api-v2-ml-rebalance-train"),
    path("ml/autofee/suggestions/", ml_autofee_suggestions, name="api-v2-ml-autofee-suggestions"),
    path("ml/autofee/history/", ml_autofee_history, name="api-v2-ml-autofee-history"),
    path("ml/escalation/config/", ml_escalation_config, name="api-v2-ml-escalation-config"),
    path("ml/actions/execute/", ml_execute_action, name="api-v2-ml-execute-action"),
    # Phase-6-C Gossip Network
    path("network/peers/", network_peers, name="api-v2-network-peers"),
    # Phase-6-F SSE endpoint
    path("events/", sse_live_events, name="api-v2-sse-events"),
]
