name: Build on release

permissions:
  contents: read
  packages: write

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-publish.yml
    with:
      tag: ${{ github.event.release.tag_name || 'latest' }}
    secrets: inherit

  build_ml:
    uses: ./.github/workflows/docker-publish.yml
    with:
      tag: ${{ github.event.release.tag_name || 'latest' }}
      build_target: final-ml
      tag_suffix: '-ml'
    secrets: inherit
